### ISSUE TITLE
Partition that implements BufferAt

### ISSUE THREAD

**Issue by awcullen** [djherbis/buffer#7]
What do think about adding ReadAt, WriteAt to Partition?

**Comment by djherbis** [comment]
I think we'd need to add NewPartitionAt (maybe a better name?) since the buffers inside the partition would have to all be BufferAt's not just Buffers.

Seems like a reasonable ask though. I'm open to review pull requests, otherwise I'll get around to it when I've got a little time.

Out of curiosity, do you mind sharing your use case? I'm always curious about uses, and making sure the solution is the right fit for the problem.

**Comment by awcullen** [comment]
Good idea.  I'm implementing this industrial protocol where I encode values in a buffer and then send it over a network.  Some values require I prepend them with their encoded length.  It would be easier to encode a length of 0, then the value, and then rewrite the 0 with the actual length written.

**Comment by awcullen** [comment]
I like the names.  Would I need to make a PoolAt and ListAt, too?

**Comment by djherbis** [comment]
Any reason you don't just do something like this?
https://play.golang.org/p/zMQ5C7Pntr_6

I assume you can't use one of the standard serialization formats or protobuf or something.

Otherwise yeah we'd probably need at least PoolAt, List might be okay since it's used internally we could just type assert.

**Comment by awcullen** [comment]
That's a great idea to pass  (multi) reader instead of one big buffer.  Let me think about that...

**Comment by awcullen** [comment]
I've ported a c# library that is buffer happy. https://github.com/OPCFoundation/UA-.NETStandard/blob/master/Stack/Opc.Ua.Core/Stack/Bindings/BufferManager.cs
Your library is working very well.

**Comment by djherbis** [comment]
Glad the library is helpful, though I'm still not sure that it will be the best solution for the problem you described (just didn't want to make more work for you when io.MultiReader would probably be sufficient, possibly more efficient as well).

Going forward with reviewing the pull request anyway as it seems like a decent addition either way.

**Comment by janekolszak** [comment]
Are you planning to merge it?

**Comment by djherbis** [comment]
Resolved by #8
